export const events = [
    {
      imageUrl:
        "https://res.cloudinary.com/dhwbs4kk2/image/upload/v1707237226/Cod-A-Thon_id4mpp.jpg",
      eventName: "COD-A-THON",
      eventDescription:
        "GDSC IET DAVV'S very own competitive programming competition which happened last year made students learn, grow and realize that 'Winning isn't everything, it's only thing'",
      collabWith: [],
      date: "Apr 7, 2023",
      time: "1:00 pm",
      venue: "IET DAVV",
      registrationUrl: "",
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dhwbs4kk2/image/upload/v1707237227/TechUnleash_jakmx4.jpg",
      eventName: "TechUnleash",
      eventDescription:
        "With the programming running in our veins and codes beating in our hearts, We the team GDSC IET DAVV encouraged students to join our club and gain knowledge about programming through our idea 'TechUnleash'.",
      collabWith: [],
      date: "Aug 18, 2023",
      time: "3:00 - 4:00 pm",
      venue: "M Block Auditorium, IET DAVV",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/dhwbs4kk2/image/upload/v1707237226/Cloud_mcuhe8.jpg",
      eventName: "Google Cloud Facilitator Program 2023",
      eventDescription:
        "We provided a program to help students boost their career in cloud computing and AI. GDSC IET DAVV also provided access to full-fledged courses provided by Google, with many surprises and goodies!",
      collabWith: [],
      date: "Aug 31, 2023",
      time: "2:00 pm",
      venue: "--",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/dhwbs4kk2/image/upload/v1707237226/Code_Quest_qdiyfy.jpg",
      eventName: "CodeQuest 2023",
      eventDescription:
        "To let our students flex those coding muscles, we brought a coding contest. And guess what? It turned out to be an epic saga of coding events which gave us memories to remember and learning to never forget!",
      collabWith: [],
      date: "Sept 21, 2023",
      time: "6:00 - 7:00 pm",
      venue: "--",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/dhwbs4kk2/image/upload/v1707237227/Invento_x18oah.jpg",
      eventName: "GDSC Volunteer meet-up",
      eventDescription:
        "We believe that if there's a name it's because of the family. We couldn't be more grateful to our volunteers for always being there with us. And We showed them our respect and thankfulness by organizing a meet up with them. We had fun, made memories, and promised to stay and grow with GDSC IET DAVV.",
      collabWith: [],
      date: "Sept 22, 2023",
      time: "2:00 pm",
      venue: "Outside Library, IET DAVV",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/dhwbs4kk2/image/upload/v1707237226/Hacktober_Fest_sszqj6.jpg",
      eventName: "Hacktoberfest",
      eventDescription:
        "In collaboration with GDSC IIPS and GDSC SDSF We GDSC IET DAVV successfully organized an event which sent for learners to contribute to open source projects and enhance their coding skills!",
      collabWith: [
        {
          name: "GDSC IIPS",
          url: "https://gdsc.community.dev/iips-international-institute-of-professional-studies-davv-indore/",
        },
        {
          name: "GDSC SDSF",
          url: "https://gdsc.community.dev/school-of-data-science-and-forecasting-indore/",
        },
      ],
      date: "Oct 7, 2023",
      time: "12:00 noon",
      venue: "Google Meet",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/dhwbs4kk2/image/upload/v1707237226/Code_Series_vl5xap.jpg",
      eventName: "CODE SERIES",
      eventDescription:
        "30 Day's coding session which made all of us say code like a pro, compile like a dope. Our students believed in their own selves and stood their grounds to achieve this challenge given by us. It was definitely a Proud moment for us to see our students believe in their coding ability!!",
      collabWith: [],
      date: "Dec 10, 2023",
      time: "--",
      venue: "Hackerrank",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/startup-grind/image/upload/v1/gcs/platform-data-dsc/events/%28For%20Bevy%29%20solutionchallenge-2022-EventThumbnail_oSBXFzI_OSGKhiA.png",
      eventName: "Solution Challenge",
      eventDescription:`The Google Developer Student Clubs 2023 Solution Challenge mission is to solve for one of the United Nation&#39;s 17 Sustainable Development Goals using Google technology. Google invites students across the world to present their ideas and solutions on this. Join this Info Session on Solution Challenge 2024 and gain insights from the previous winning team Wonder Reader from Indonesia.`,
      collabWith: [{name:"GDSC Vaishnav", url:"https://gdsc.community.dev/shri-vaishnav-vidyapeeth-vishwavidyalaya-indore/"}],
      date: "Dec 13, 2023",
      time: "07:30 pm",
      venue: "Online",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/startup-grind/image/upload/v1/gcs/platform-data-dsc/events/session.1.png",
      eventName: "Intro to Machine Learning",
      eventDescription:`We'll explore how machines learn from data to make decisions, revolutionising technology and shaping our future. Don't miss out on this dynamic introduction! 🤝 In Collaboration with: GDSC IIST`,
      collabWith: [{name:"Anurag Mukati", url:"https://in.linkedin.com/in/anurag-mukati"}, {name:"GDSC IIST", url:"https://gdsc.community.dev/indore-institute-of-science-technology-indore/"}],
      date: "Jan 26, 2024",
      time: "05:00 pm",
      venue: "Online",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/startup-grind/image/upload/gcs/platform-data-dsc/events/WhatsApp%20Image%202024-02-04%20at%2017.06.06%20%281%29.jpeg",
      eventName: "MOI Blockchain Dev X Bootcamp",
      eventDescription:`From the Basics to Building applications on the MOl blockchain.`,
      collabWith: [{name:"Central DAO", url:"https://centraldao.in/"}, {name:"MOI", url:"https://moi.technology/"}],
      date: "Feb 07, 2024",
      time: "02:30 pm",
      venue: "M-Block Auditorium",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/startup-grind/image/upload/v1/gcs/platform-data-dsc/events/Screenshot%202024-02-20%20at%2010.48.43%E2%80%AFAM_sWwWA2y.png",
      eventName: "Intro to Flutter",
      eventDescription:`Explore Flutter fundamentals, network, and learn from the best and solve your all the queries.`,
      collabWith: [{name:"Sarika Purohit", url:"https://in.linkedin.com/in/sarika-purohit"}, {name:"GDSC IIST", url:"https://gdsc.community.dev/indore-institute-of-science-technology-indore/"}],
      date: "Feb 20, 2024",
      time: "8:00 pm",
      venue: "Google Meet",
      registrationUrl: "",
    },
    {
      imageUrl: "https://lh3.googleusercontent.com/d/10JKtHZ0KN1deerBRCx4JNjM8EsO6G42W?q=75",
      eventName: "Google Cloud Felicitation Ceremony",
      eventDescription:`Finally, the wait is over! Join GDSC IET DAVV for an exciting event filled with entertainment, fun and most importantly, the heavily awaited Google Cloud Swags. You are all officially invited to the Google Cloud Felicitation Ceremony!`,
      collabWith: [],
      date: "Mar 01, 2024",
      time: "03:30 pm",
      venue: "B-101, B Block",
      registrationUrl: "",
    },
    {
      imageUrl: "https://res.cloudinary.com/dipv4294k/image/upload/v1710774914/pxcpq8osxfmglbxcjeni.jpg",
      eventName: "UI/UX Unleash",
      eventDescription:
        "Dive deep in the intricate concepts of UI/UX and Figma, Join us for an immersive UI/UX workshop hosted by GDSC IET DAVV,  where you'll learn the latest techniques and best practices to craft intuitive, user-centric interfaces. Get hands-on experience and elevate your design skills to the next level.",
      collabWith: [],
      date: "Mar 20, 2024",
      time: "3:00 pm",
      venue: "B-101, B Block",
      registrationUrl: "https://lu.ma/xkcylx1b",
    },
  ];
